include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_equals_and_hash_code_on_mutable_classes: ignore
  language:
    strict-inference: false

  exclude:
    - /**/*.g.dart
