name: bobs_jobs
description: Lightweight, descriptive functional programming for pragmatic Dart developers.
version: 0.0.1-dev.14
repository: https://github.com/JakesMD/dart-bobs-jobs

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  test: ^1.25.7

dev_dependencies:
  mocktail: ^1.0.4
  test_beautifier: ^1.1.0
  very_good_analysis: ^7.0.0
