name: bobs_jobs
description: Functional programming with a pinch of salt.
version: 0.0.1-dev.3
repository: https://github.com/JakesMD/dart-bobs-jobs

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  test: ^1.25.7

dev_dependencies:
  mocktail: ^1.0.4
  test_beautifier: ^1.1.0
  very_good_analysis: ^6.0.0
